//import type { NextPage } from 'next'
import Head from 'next/head'

const Home: React.FC = ()=>{
  return (
    <div>
      <Head>
        <title>Vendas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     Bem vindo!
     <button className="button is-dark">Button</button>
    </div>
  )

}

//const Home: NextPage = () => {
  export default Home;

  



